export { default as list } from './pages/dashboard/components/List/List';
export { default as card } from './pages/dashboard/components/card/Card';
export * from './components';
export { default as profilelist } from './pages/dashboard/components/profile-list/ProfileList';
export { default as SideBar } from './components/sidebar/SideBar';
export { default as layout } from './layout';
export { default as page } from './page';
export * from './pages/dashboard';
export { default as LeftNav } from './pages/employees/components/LeftNav/LeftNav';
export { default as MainSection } from './pages/employees/components/MainSection/MainSection';
export { default as Card } from './pages/employees/components/MainSection/components/Card';
export { default as EditDetailsModal } from './pages/employees/components/ModelPopup/EditDetailsModal';
export { default as ModelPopup } from './pages/employees/components/ModelPopup/ModelPopup';
// export { default as TopNav } from './pages/employees/components/TopNav/TopNav';
export { default as Employees } from './pages/employees/page';
export * from './pages/employees/types';
// export * from './pages/face-detect';
// export * from './pages/face-register';
export * from './pages';
export * from './services';
export * from './types';
export * from './utils/alerts/Alert';
export * from './utils';
export { default as uuid } from './utils/uuid/Uuid';
